### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by hsluoyz** [casbin-rs/actix-file-adapter-rbac#2]
https://github.com/casbin-rs/actix-file-adapter-rbac/runs/7939298784?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/185795752-76d3faba-eeb8-49d9-8bc2-b066025c0887.png)

**Comment by hsluoyz** [comment]
@SiddheshKanawade 

/cc @hackerchai

**Comment by SiddheshKanawade** [comment]
#3 solves this

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casbin-rs/actix-file-adapter-rbac/pull/3
